### ISSUE TITLE
ログインリダイレクトや（ゲームエラーによる）ページリロードにおいてもCSSを反映するべき

### ISSUE THREAD

**Issue by sakuraEsan** [otiai10/demado#102]
## 使用環境
| アイテム | 名称 |
| ------------- | ------------- |
| 使用OS | windows10|
| ブラウザ |chrome Iron|
| demadoバージョン |BETA版v2.0.23 |
| その他拡張機能 |demado(正式版) |
| 再現性 |確認した限り毎回 |

### 問題が発生するまでの手順
 ~~demadoで適当なページを開いた後にdemadoでページ再読み込み~~

レフトナビが表示されるブラウザゲーム（[DeepOne](https://pc-play.games.dmm.com/play/deepone/)及び [あいりすミスティリア！](https://pc-play.games.dmm.com/play/imys/)）にて検証
CSSには　#leftnavi,#dmm-left-navi .dmm-ntgnavi{display:none;}　を書き込んだ状態とコメントアウトした状態の2種で検証

### 症状
 ~~ページ再読み込みやログイン処理等でページ遷移があった際、 遷移後のページにCSSとズーム倍率が反映されない~~

- 上記CSSを書き込んだ状態だとレフトナビが消えた状態のままスクロールバーだけが表示される

- 上記CSSをコメントアウトした状態だとレフトナビがでたままスクロールバーが表示される

このことから、恐らくCSSは反映されておりました。（勘違いしてしまい申し訳ない）
また、
- ズーム倍率は等倍（1倍）に戻るという訳ではなくタイトルバーから確認したところ67%以上80％以下(恐らく75%？)
### 要望
~~ ページ遷移後にもCSS及びズーム倍率を反映していただければ幸いです~~
ページ遷移後にもスクロールバー非表示でズーム倍率を設定した値にしていただければ幸いです

**Comment by otiai10** [comment]
> demadoでページ再読み込み

これは、demadoでつくったウィンドウの中で、F5などの方法でリロードをした、という意味ですか？

**Comment by sakuraEsan** [comment]
これまでは、ウィンドウ上のタイトルバーから再読み込みで行いましたが、F5でも同様でした。
また、こちらでの検証にて上記問題点に追記修正したい部分がありましたので変更させていただきます。

**Comment by otiai10** [comment]
demadoで開いたあとのウィンドウを再読み込みしたい場合ってどんなときですか？
基本的には、demadoで開いたウィンドウはdemadoから開いて読み込んんだものしか認識しないのが正しい挙動で、再読み込みは対処していないです。

ただ、「再読み込みする」が明らかに真っ当なユースケースなのであれば、対応しないといけないなと思っているところです

**Comment by sakuraEsan** [comment]
- ブラウザゲーム内でエラーが起きたためゲーム側から再読み込みをお願いされる(下記画像一例)
- DMMに限って言えば、ログアウトした状態からゲームを起動しようとするとdemadoで指定したURLの前にログイン画面→ゲームとなるためdemadoで開いたウィンドウ内でログイン処理をしようとすると、ページ遷移が起きてしまう。

自分の環境だと上記2点になります
お忙しいところ誠に申し訳ありませんがお手すきの際にご一考くださると幸いです
![error2](https://github.com/user-attachments/assets/277a69a4-1a5f-4091-96ae-6c93d4ed5747)

**Comment by otiai10** [comment]
うーん、たしかに。艦これは猫多いですもんね... たしかにそうだ

**Comment by otiai10** [comment]
ログインのリダイレクトも、思ったより声が多いので、対応すべきですね
ありがとうございます
