### ISSUE TITLE
demadoからウィンドウを開くボタンを押した直後に別の画面をアクティブにすると、ウィンドウ設定が無視された状態で開かれる

### ISSUE THREAD

**Issue by aska-333** [otiai10/demado#115]
# 環境
- 拡張のバージョン: 2.0.35 公開版
- OS: Windows
- Chromeのバージョン: Not/A)Brand 8 / Chromium 126 / Google Chrome 126
(ブラウザはvivaldiを使用しています)

# 事象の詳細
demadoから何かを開こうとして、新規ウィンドウが出る前に別の画面をアクティブにしたり
demadoから複数のものを一度に開こうとすると、開かれたウィンドウはウィンドウ設定が適用されていない状態で開かれる

# 再現頻度
毎回

# 再現方法
demadoに複数のものを登録して、登録したウィンドウを上から順にポンポン押して開く、または
demadoに登録したものを押して、新規ウィンドウが開かれる前に別の画面をアクティブにする

# いつから起きているか
8月15日くらいから？

# どう困っているか
設定が無視されているのでだいぶ困る

# 開発者にひとこと
休息は大事です、ご自愛ください。

**Comment by otiai10** [comment]
#101 とも同じ現象ですかね

**Comment by aska-333** [comment]
> #101 とも同じ現象ですかね

そのようです、他の方の報告の確認の方法がわからず重複した報告になってしまいました。失礼しました。

**Comment by otiai10** [comment]
もしよければ #101 のほうにコメントしておいていただけるとさいわいです https://github.com/otiai10/demado/issues/101#issuecomment-2308007158
