### ISSUE TITLE
ブラウザで普通にゲームを開いた時に上と左がトリミングされてスクロール不能になってしまう

### ISSUE THREAD

**Issue by aorenjar** [otiai10/demado#13]
いつも便利に使わせてもらっています。

当方DMMの「刀剣乱舞」を遊ぶのに使わせていただいていますが、運営からのお知らせ等を読みたくて、普通のタブでゲームを開くことがあります。その時、demadoの独立窓で開いた時のように上と左がトリミングされ、下へのスクロールが全くできないという状態にいつも陥ってしまい、少し不便に思っております。

現在使っている環境はSRWare Iron（Chromium系ブラウザのひとつ）ですが、Google Chromeを使っていた時も同様の問題は起こっていました。

「艦これウィジェット」では普通のタブで開いた時、トリミングされたり、スクロール不能に陥ったりということはありません。

素人なので何が違うのか分かりかねるのですが、対処方法があれば教えていただきたいと思いますし、ソフトウェア側の不具合（もしくは現在の仕様）であるなら、改善をお願いできませんでしょうか。

**Comment by otiai10** [comment]
@aorenjar 
いつもありがとうございます。
demadoの0.1.20で、「一時的にdemadoらない」というボタンができたので、それを押してもらうと解決しますでしょうか？お試しください

![2015-03-09 17 03 26](https://cloud.githubusercontent.com/assets/931554/6551587/529d486a-c67e-11e4-874f-b515210b6323.png)

**Comment by aorenjar** [comment]
このボタンで試したところできました！

一時無効ボタンを押す→ブラウザで開く、ですね。
ありがとうございました！

**Comment by otiai10** [comment]
![](http://img.tiqav.com/Oj.jpg)
