### ISSUE TITLE
スクリーンショットボタンが機能しない

### ISSUE THREAD

**Issue by SuwakoFrog** [otiai10/demado#132]
# 不具合概要
特定動作でスクリーンショットボタンを押した際、スクリーンショットを撮影することができない

# 環境
Windows11
Google Chrome バージョン: 128.0.6613.120（Official Build） （64 ビット）
demado 正式版 v2.0.55

# 再現手順
1. chromeのアドレスバー横にピン留めされたdemadoの拡張機能アイコンを押下
2. 開かれたメニューから、現在動作中のdemadoウインドウのスクリーンショットボタンを押下
3. 一瞬ファイル保存ダイアログと思われるウインドウが開くが、即座に閉じられる(内容描画前にウインドウが消えるので、一瞬開かれているっぽいウインドウの詳細は不明)

# 備考
ダッシュボードを開いて、ダッシュボード経由でスクリーンショットを撮影する場合は正常に動作しています

**Comment by otiai10** [comment]
ありがとうございます。実は保存されてる、ってことはないですか？

**Comment by SuwakoFrog** [comment]
chromeの自動保存機能はオフです(常に保存先選択ダイアログが出る設定)
ダウンロードフォルダ、ピクチャフォルダ、デスクトップにもファイルはありませんでした
cxhromeのダウンロード履歴にも何ものっていませんでした

**Comment by otiai10** [comment]
https://github.com/otiai10/demado/blob/ea35826067dc5821671ae7d132beaa1efb50061a/src/components/popup-control/index.tsx#L28

ここで、downloadが終わる前に、window.closeが走ってる気がしますね。
単に、window.closeしなければいいだけだと思う。

**Comment by SuwakoFrog** [comment]
Beta2.0.56にて問題なく動きました
修正ありがとうございます
