### ISSUE TITLE
一部のゲーム画面右にスクロールバーが追加されレイアウトが崩れる

### ISSUE THREAD

**Issue by Derliss344** [otiai10/demado#140]
ゲームURL（とのフラ）
https://play.games.dmm.com/game/deepone

**Comment by otiai10** [comment]
どのように崩れますか？
どんなときに崩れますか？
再現頻度はどの程度ですか？
お使いのOSおよびChromeのバージョンはなんですか？

**Comment by Derliss344** [comment]
①ゲーム画面にスクロールバーがめり込む
②demadoで起動時から
③17日のゲームのメンテナンス以降常時
④Windows10 Pro 22H2、Chrome 128.0.6613.138

恐らくゲーム画面横のスクロールバーを非表示にする設定を書けばよいと思うのですが、書き方が分からず…

**Comment by otiai10** [comment]
スクショ貼れますか？

**Comment by Derliss344** [comment]
すいません。出先なので難しいです

**Comment by Derliss344** [comment]
![1411001](https://github.com/user-attachments/assets/c80e72f2-d117-4913-920d-93a0b5e91388)
遅くなりましたが、オフセット整えてこんな感じです

**Comment by sakuraEsan** [comment]
自分も同じ現象で困っていまして
CSSに下記を書き加える事でとりあえず落ち着いたのですが、
ウェブページに疎く正しい対処なのか分かりませんが、何か参考になれば幸いです。
.css-77bp4q {display: block;}

**Comment by otiai10** [comment]
設定をexportしてこちらで添付いただけませんか？できればでいいです

**Comment by sakuraEsan** [comment]
[deepone 1.0倍設定](https://github.com/user-attachments/files/17058957/deepone.json)

こちらでよろしいでしょうか。

**Comment by otiai10** [comment]
ありがとうございます！

**Comment by otiai10** [comment]
当方、MacBook Air ですが、下記の設定で正しく動作しています。どうでしょうか

[deepone-macbook.json](https://github.com/user-attachments/files/17106083/deepone-macbook.json)

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/a2612e32-6071-4434-a239-7ffd189d96d4">

**Comment by Derliss344** [comment]
お二人ともありがとうございます
設定ファイル読み込んでみましたが変わらず画面表示領域内右側にスクロールバーが表示されていました
【.css-77bp4q {display: block;}】をcssに追記でとりあえず今はなんとかなりました

**Comment by sakuraEsan** [comment]
## 使用環境
| アイテム | 名称 |
| ------------- | ------------- |
| 使用OS | windows10|
| ブラウザ |chrome 129.0.6668.59|
| demadoバージョン |BETA版v2.0.57 |
| その他拡張機能 |demado(正式版) |

自分も上記環境で試しましたが一番上のスクショのようにスクロールバーが表示されていました。

**Comment by otiai10** [comment]
本件、申し訳ないですがdemado側標準としての対処はなく、設定における

```
.css-77bp4q {display: block;}
```

が解法ということでファイナルアンサーな気がします。すみません...

**Comment by Derliss344** [comment]
なるほど了解しました。
お時間割いていただきありがとうございました。
