### ISSUE TITLE
ダッシュボードが開かない

### ISSUE THREAD

**Issue by hiropon004** [otiai10/demado#145]
# 環境
- 拡張のバージョン: 2.0.59 公開版
- OS: Windows
- Chromeのバージョン: Not/A)Brand 8 / Chromium 126

# 事象の詳細
デュアルディスプレイの配線を変えた（2本のHDMIのうち1本をDVI-Dに変更）
BIOSの設定で、マザボのグラボを使わないように変更した
グラボからDVI-DとHDMIでのデュアルディスプレイ環境にした

それから、OS再起動してからのブラウザ起動で、ダッシュボードが開かなくなった

# 再現頻度
常時

# 再現方法
開かないので、再現方法不明

# いつから起きているか
配線組み換え後から

# どう困っているか
ダッシュボードが開かないので、そこからのゲーム起動ができず不便

# 開発者にひとこと
 特になし

**Comment by otiai10** [comment]
ありがとうございます。
ダッシュボードを開くボタン（画像右下）を押したら、このボタンが表示されているポップアップ自体は閉じますか？

<img width="332" alt="image" src="https://github.com/user-attachments/assets/6d2d3d7e-04eb-4797-ab30-61d79f272cab">

**Comment by hiropon004** [comment]
ポップアップ自体は、ダッシュボードボタン押下関係なく、閉じることができますー

**Comment by otiai10** [comment]
現時点でのおそらくの予想ですが、前の構成のときの座標を記憶してしまっていて、現在の構成で同じ座標で開こうとしているのではないかと想像してます。

ので、いったん「ダッシュボードの座標を 0,0 に初期化する」という機能を早急にリリースしようと思います

**Comment by hiropon004** [comment]
一応demadoの再インストールをしたら、設定が初期化されたためか、ダッシュボードが表示されるようにはなりましたのでご報告

リリース自体は、まだでしたかね？

**Comment by otiai10** [comment]
ありがとうございます。その挙動である程度仮説の確度が上がりました。v2.0.60出すので、お待ちください

**Comment by otiai10** [comment]
v2.0.60 出しましたので、ご確認ください

**Comment by hiropon004** [comment]
ダッシュボードの位置、初期化できるようになっていたこと確認できました。

ありがとうございました。

閉じますー

**Comment by hiropon004** [comment]
ダッシュボードの位置、初期化できるようになっていたこと確認できました。

ありがとうございました。

閉じますー
