### ISSUE TITLE
リロード

### ISSUE THREAD

**Issue by sou51379** [otiai10/demado#22]
リロードボタン（ショートカットキー）とリロード時の再度位置調整ができるようにして欲しい。
DMMのゲームだと一定時間経つと接続が切れるものがあり、Flashの画面のままではF5が使えない。そのため開き直す必要が有り面倒である。
まあ最悪リロード時に位置なおしてくれるだけで解決できるのでこちらをお願いしたい所。
あと、古い設定引き継いで明らかにずれるのは仕様ですか？

**Comment by otiai10** [comment]
> そのため開き直す必要が有り面倒である。

僕はあんまり面倒を感じません。

> まあ最悪リロード時に位置なおしてくれるだけで解決できるのでこちらをお願いしたい所。

おっしゃる通りですが、リロード欲しいと思ったときにやります。

> あと、古い設定引き継いで明らかにずれるのは仕様ですか？

仕様です

**Comment by sou51379** [comment]
お返事ありがとうございます。
DMMのフラワーナイトガールと言うゲームのR１８版でなのですが、窓を開きながら調整するモードで設定しなおして再度demado側から開いてもずれるんですが、こちらも仕様ですか？
具体的には横960縦640で設定してもずれて、横977縦677で設定すればずれないという状況です。

**Comment by otiai10** [comment]
いくつか報告いただいてます。

> 具体的には横960縦640で設定してもずれて、横977縦677で設定すればずれないという状況です。

まさにこれが聞きたかったです！めちゃくちゃ助かります！

**Comment by sou51379** [comment]
なるほどそうでしたか。ありがとうございます。
また何かありましたらご報告させていただきます。

**Comment by sou51379** [comment]
複数回起動し直さないとちゃんとゲーム画面が左上にピッタリ来ないっぽいのもバクですかね？
何回か1回にはちゃんと左上にピッタリ来るんですけども…。

**Comment by otiai10** [comment]
お手数ですが、頻度を記録していただいていいですか。日時があるとより助かります

**Comment by otiai10** [comment]
related #24
