### ISSUE TITLE
offsetが効いたり効かなかったりする事象

### ISSUE THREAD

**Issue by yaizawa2e** [otiai10/demado#24]
お世話になっております。
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
な環境でdemadoを使い始めましたが、offsetが効いたり効かなかったりする事象が発生しています。
今のところ再現条件が把握できておりませんが、offsetが効かない場合がほとんどになっています (逆に言うとwidth、heightは効いている)。
またoffsetが効かずに起動した場合はスクロールバーも表示されています。
目玉ボタンで立ち上げるとやはりoffsetが聞きませんが、offsetの数字をいじると即座に反映されます。
デバッグ情報等取得が必要なものがあればご教示いただけますでしょうか。

ちなみにご参考になるか分かりませんが艦これウィジェットは正常に表示されております。

なお上記UA情報でほぼ環境はおわかりかとは思いますが、OSはWindows 10 Home 64bit (英語版) です。

**Comment by otiai10** [comment]
@yaizawa2e ありがとうございます。
これは、窓をどこから立ち上げたものですか？

**Comment by yaizawa2e** [comment]
ボタンから起動、config画面のリンクから起動いずれも発生します。
(ちなみに某モン娘オンラインです)

**Comment by otiai10** [comment]
めっちゃお手数おかけし申し訳ないんですが、まずは

バックグラウンドページ

<img width="609" alt="2015-12-25 14 48 32" src="https://cloud.githubusercontent.com/assets/931554/12000289/0a1d269a-ab17-11e5-8fd6-f78cba8983fa.png">

の `Console` で、起動したときなんか起きてないか拝見したいですmm

**Comment by otiai10** [comment]
で、可能なら、起動して開いた窓の、要素の検証から `Console` で何か起きてないか拝見したいです。

お手数おかけし申し訳ないです

**Comment by yaizawa2e** [comment]
特にDeveloper ToolsのConsoleには出ていないようです。
![2015-12-24](https://cloud.githubusercontent.com/assets/16421395/12000317/0b4c004c-aa89-11e5-8bf4-6eb4efdba770.png)

要素の検証にはなにか出ていますが…広告関連っぽいですね。
![2015-12-24 1](https://cloud.githubusercontent.com/assets/16421395/12000321/3818aa58-aa89-11e5-9565-6b8e91407c4b.png)

**Comment by sou51379** [comment]
#22から
記録をとりあえず気づいたお昼ごろから取らせていただいてます。
あとSSも添付しますね
2015/12/25　12：39ズレ
2015/12/25　12：39ズレ
2015/12/25　12：39正常
2015/12/25　12：39正常
2015/12/25　14：57ズレ
2015/12/25　14：59ズレ
2015/12/25　15：00正常
![screenshot_20151225145906](https://cloud.githubusercontent.com/assets/7306048/12000349/34c86d4a-ab18-11e5-8a3a-2cc27ff9360e.png)
多分3度目以降ログインしている状況でなおるのでしょうか？

**Comment by otiai10** [comment]
あーログインしてない場合は必ず「動作しない」ですね...それは確実に言えます。
あと、リダイレクトとかしてると動作しない...

ちょっとわかってきたかも

**Comment by otiai10** [comment]
0.2.3で、それっぽい修正してみました

**Comment by yaizawa2e** [comment]
迅速なFixありがとうございます、今のところ問題なく動いております!

…これはAmazonウィッシュリストでビールでもお送りせねば…。
