### ISSUE TITLE
demadoウィンドウ立ち上げ時にドラッグしていると枠が切れた状態になる

### ISSUE THREAD

**Issue by mocho88** [otiai10/demado#48]
demadoウィンドウが出た瞬間にその枠を掴んでドラッグ移動をし続けると、枠のサイズを合わせる処理が無効化されるっぽいです。

[ドラッグにより枠の端が切れた状態]
![2](https://user-images.githubusercontent.com/4847353/117557788-a7738d80-b0b1-11eb-8936-22f60c857848.png)

[正常な状態]
![1](https://user-images.githubusercontent.com/4847353/117557785-a2aed980-b0b1-11eb-89cc-21fc94991d72.png)

**Comment by mocho88** [comment]
返信ありがとうございます。
確かにdemadoが立ち上がってサイズ変更が終わるまでの間0.2秒ほど待てばいいだけですが、癖で枠を触って動かしてしまうんですよね。

個人的に、
   src/js/page-decorator/app-decorator.js
   ※窓の外枠の大きさを調整する処理
の部分を何の処理もしないよう変更し、
枠を触っても触らなくても同じ枠サイズになるようにして使っています。

私のようにdemadoヘビーユーザーなら気になる挙動になるのかな、と思って報告させていただきました。

**Comment by otiai10** [comment]
@mocho88 
> 私のようにdemadoヘビーユーザー

ありがとうございます！最近demadoのメンテナンスぜんぜん出来てなかったですが、こう言っていただけて、励みになります。
メンテナンスしていくにあたって、ご意見伺うこともあると思いますが、今後もご協力いただけるとうれしいです。
