### ISSUE TITLE
画面閉じるときの警告を出す設定がほしい

### ISSUE THREAD

**Issue by otiai10** [otiai10/demado#94]
[ref](https://x.com/indjpn1/status/1824915686675874293)

**Comment by indjpn** [comment]
要望のポストを投稿した者です。
この度は大変軽率で不躾な事をしてしまい申し訳ありませんでした。
また、新しいスレッドを立ててお詫びをするべきか悩みましたがこちらのスレッドを利用させていたくことにいたしました。
もしこれがgithubのルールに反した行いだったりマナー違反だった場合はどうかご容赦いただけますと幸いです。


＞ 以前のように「全ての設定に対して警告を有効」にすべきか、新たに「個別の設定に対して警告を有効」にすべきか、どっちがいいですかね？

私としては前者のほうがありがたいです。
ですが技術的な問題などございましたらどちらでも結構でございます。

最後に、他人の気持ちを考えず軽率な行いをしてしまったことについて改めてお詫び申し上げます。
以後気をつけます。
私からは以上です。
失礼いたします。

**Comment by otiai10** [comment]
@indjpn 全然いやな気持ちになったりとかはしてないので謝らなくていいです。むしろご意見いただけて嬉しいです 😊 

単に、拾うのが大変なので、メンションしてくれ、というただ文字通りの意味だけです 🙇
